### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by Govind-S-B** [Govind-S-B/ExamHall-SeatAllocator#11]
The current allocation algorithm is really bloated and needs a complete code refactor 
A few issues that I have noticed are

 - the drawing hall allocation logic loops through previously allocated halls twice , I have a quick bandage fix implemented there for it to not cause an issue but the underling issue is still there
`len(Hall_structure[i][j])<3:`

- Some random seeds perform better than the current default allocation . My assumption was that the default allocation performs the best since it sorts and allocates the biggest halls and classes first

**Comment by officiallyaninja** [comment]
Add a virtual environment for all of the modules

**Comment by Govind-S-B** [comment]
Entire codebase has changed
