### ISSUE TITLE
Error Handling : Input validation for text field inputs , Passing exit codes to Flutter

### ISSUE THREAD

**Issue by Govind-S-B** [Govind-S-B/ExamHall-SeatAllocator#60]
Input validation for text field inputs which make the allocator crash
 eg:  entering no values and adding null values to DB
```
+----+---------+
| ID | Subject |
+----+---------+
|  1 | English |
|  - |         | <-- Invalid Values
+----+---------+

```

Passing error codes from rust , python for proper error messages , such as when students > capacity available

**Comment by officiallyaninja** [comment]
I'll be printing out the error message from rust into stdout, you can read stdout from subprocesses in flutter, so those of you on the flutter team just look into that.  
I'll also be giving unique exit codes for each type of error.
