### ISSUE TITLE
Toggleable Experimental Feature : Random distribution within the same subject

### ISSUE THREAD

**Issue by Govind-S-B** [Govind-S-B/ExamHall-SeatAllocator#64]
### Describe the problem or issue the feature resolves  

If the subjects count are the same and the students count are the same for multiple days , the same set of students end up writing in the same halls again and again

### Mention and describe the feature  

Add a randomizer or something to shuffle students of the same subject / same class ( since too wide can cause a class to have multople outgoing classes ) to be shuffled around so that its not the same hall everyday / or the same people around everyday

### Mention the merit of implementing the feature and the improvements it offers  

reduces chances of cheating since now the seat positions are not predicable

**Comment by officiallyaninja** [comment]
I think it'll be better to divorce this from the allocator, since this is sort of a different thing, and we don't want to bloat it.  
i think we should create a python script that reads from and updates report.db

**Comment by Govind-S-B** [comment]
![image](https://github.com/Govind-S-B/ExamHall-SeatAllocator/assets/62943847/df771708-a261-4418-b01f-b35eee396980)

we could do something like have a utils.py which then contains the pdf_generator and the new random_spacer functionality . This solves the issue of having to make multiple python bundles by packaging it all into a single file

Also  this adds more extendibility to our code , we can add more python modules to this as sub modules and use them as needed . utils.py will act as the common entry point

**Comment by officiallyaninja** [comment]
well after some discussion and thinking, I think what would be best is just to randomize the halls vector in the rust allocator, so each time a different hall will be filled first.  
since this is to be a toggleable feature it should probably be a CLI argument, and if we're adding that as a CLI argument then the paths to `hall.db` and `report.db` should also probably be arguments instead of being hardcoded in the allocator

so this will require a little bit of work on the flutter side to add in the appropriate CLI arguments

**Comment by officiallyaninja** [comment]
alright, so this is how the CLI args will work.  
the first argument is the path to the input database. in our current case, it is `input.db`  
the second argument is the path to the output database. in our current case, it is `report.db`  
and there is an optional flag to randomize the halls. either `-r` or `--randomize`  
so in our current case it will look like   
`./allocator input.db report.db` without randomization   
`./allocator input.db report.db -r` or `./allocator input.db report.db --randomize` with randomization
