### ISSUE TITLE
Functionality issue in Subject entry and suggestions list.

### ISSUE THREAD

**Issue by jydv402** [Govind-S-B/ExamHall-SeatAllocator#65]
### Describe the problem or issue the feature resolves  
The issue is in the Subject entry text field and suggestions list on the Students page. 

Currently, the suggestions list of subjects works by manually adding subjects to the list by entering the subject in the text field and clicking the add button. If the user enters the subject and forgets to click on the add button, the students' list will be created without any data in the subject cell or some random subject that was already in the suggestions list. Also, it is quite cumbersome to click the add button every time the user enters a new subject. 

### Mention and describe the feature 
 It would be better if the manual addition of subjects would be removed and implement a new way to populate the suggestions list. Preferably we can use the [Autocomplete ](https://api.flutter.dev/flutter/material/Autocomplete-class.html)widget inbuilt to flutter that can suggest from a predefined list of subjects.

### Mention the merit of implementing the feature and the improvements it offers 
The proposed new feature does away with the possibility of assigning null or wrong data to the subject entry during the students' list is created.

**Comment by Govind-S-B** [comment]
@officiallyaninja fixed this in dev with latest merge
