### ISSUE TITLE
Your web app is ready! 🚀

### ISSUE THREAD

**Issue by sleepingexperiments** [Govind-S-B/ExamHall-SeatAllocator#80]
Hey! 👋

Someone has requested a demo of your project using [Ukoreh](https://ukoreh.fun/)! 🧙‍♂️.

The app compiled fine and is now live at https://flutter-preview.github.io/Govind-S-B-ExamHall-SeatAllocator

**Comment by Govind-S-B** [comment]
This was probably someone who requested a random project to be compiled .
But this project wont work on web due to the sqflite dependency and some other stuff . We built this for windows

TLDR : this does not work
